services:
  backend:
    image: backend
    build:
      context: backend/  
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_NAME=db-1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    depends_on:
      - db

  frontend:
    image: frontend
    build:
      context: frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    restart: always


volumes:
  postgres_data:
